spring:
  datasource:
    url: jdbc:mysql://localhost:3306/network_prod?serverTimezone=UTC
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
          management-base-url: http://zerone.network:9000/

linkToChange:
  password: "http://zerone.network:9000/change-password"
  email: "http://zerone.network:9000/shift-email"

upload:
  path:  "/home/jvmapps/photos"

log:
  path: "/var/log/javapro"
